#!/bin/bash
# Written By: Mr Rahul Kumar
# Modified and corrected by: Fedor Sorokin
# Update date 06-09-2017
#
LANG=en_us_8859_1

DATE=`date +%d%b%Y`
XSNAME=`echo $HOSTNAME`
UUIDFILE=/tmp/xen-uuids.txt
NFS_SERVER_IP="put_your_nfs_server_ip_here"
MOUNTPOINT="put_path_to_mount"
FILE_LOCATION_ON_NFS="put_path_in_your_nfs_server"

echo "+=================================+"
echo "| Hostname: ${XSNAME}             |"
echo "| Today is: ${DATE}		|"
echo "| UUID file:  ${UUIDFILE}		|"
echo "| Server NFS: ${NFS_SERVER_IP}	|"
echo "| Mountpoint: ${MOUNTPOINT}	|"
echo "+=================================+"

echo "Create mount point"
mkdir -p ${MOUNTPOINT}

echo "Mounting remote nfs share backup drive"
[ ! -d ${MOUNTPOINT} ]  && echo "No mount point found" && exit 0
mount -t nfs ${NFS_SERVER_IP}:${FILE_LOCATION_ON_NFS} ${MOUNTPOINT}

echo "Creating directories"
BACKUPPATH=${MOUNTPOINT}/${XSNAME}/${DATE}
mkdir -p ${BACKUPPATH}
[ ! -d ${BACKUPPATH} ]  && echo "No backup directory found" && exit 0

echo "Fetching list UUIDs of all VMs running on XenServer"
xe vm-list is-control-domain=false is-a-snapshot=false | grep uuid | cut -d":" -f2 > ${UUIDFILE}
[ ! -f ${UUIDFILE} ] && echo "No UUID list file found" && exit 0

while read VMUUID
 do
    VMNAME=`xe vm-list uuid=$VMUUID | grep name-label | cut -d":" -f2 | sed 's/^ *//g'`
    SNAPUUID=`xe vm-snapshot uuid=$VMUUID new-name-label="SNAPSHOT-$VMUUID-$DATE"`
    xe template-param-set is-a-template=false ha-always-run=false uuid=${SNAPUUID}
    xe vm-export vm=${SNAPUUID} filename="$BACKUPPATH/$VMNAME-$DATE.xva"
    xe vm-uninstall uuid=${SNAPUUID} force=true
 done < ${UUIDFILE}

umount ${MOUNTPOINT}
